import { Meteor } from 'meteor/meteor';

Meteor.startup(() => {

 //    if (!Bets.findOne()){
 //          Bets.insert({
 //            matches     : [1, 2, 3],
 //            user_id     : 0,
 //            created     : 0,
 //            modified    : 0,
 //            points      : 34
 //        });
	// }

/*

	Bets.remove({},{justOne: false});
	Meteor.users.remove({},{justOne: false});

Bets.insert({"_id":"4EsY3LsENRgayduqY","modified":"2016-06-24T13:23:43.898Z","match":[[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[{"id":1,"name":"Poland"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":6,"name":"Hungary"}],[{"id":8,"name":"Germany"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":14,"name":"England"}],[{"id":1,"name":"Poland"},{"id":4,"name":"Wales"}],[{"id":11,"name":"Spain"},{"id":12,"name":"France"}],[{"id":4,"name":"Wales"},{"id":11,"name":"Spain"}],[{"id":11,"name":"Spain"},null]]});
Bets.insert({"_id":"8Mgjj9xqSTNNGfzGw","modified":"2016-06-24T13:40:56.605Z","match":[[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[{"id":0,"name":"Switzerland"},{"id":2,"name":"Croatia"}],[{"id":4,"name":"Wales"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":10,"name":"Italy"}],[{"id":12,"name":"France"},{"id":14,"name":"England"}],[{"id":2,"name":"Croatia"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":12,"name":"France"}],[{"id":7,"name":"Belgium"},{"id":12,"name":"France"}],[{"id":12,"name":"France"},null]]});
Bets.insert({"_id":"DtK4JgXeEd8omDZTE","modified":"2016-06-24T13:45:57.879Z","match":[[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[{"id":1,"name":"Poland"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":10,"name":"Italy"}],[{"id":12,"name":"France"},{"id":14,"name":"England"}],[{"id":3,"name":"Portugal"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":12,"name":"France"}],[{"id":3,"name":"Portugal"},{"id":8,"name":"Germany"}],[{"id":8,"name":"Germany"},null]]});
Bets.insert({"_id":"Fw3og7iQrQ5Nky5Q2","modified":"2016-06-24T13:32:23.840Z","match":[[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[{"id":1,"name":"Poland"},{"id":2,"name":"Croatia"}],[{"id":4,"name":"Wales"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":10,"name":"Italy"}],[{"id":12,"name":"France"},{"id":14,"name":"England"}],[{"id":1,"name":"Poland"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":14,"name":"England"}],[{"id":7,"name":"Belgium"},{"id":8,"name":"Germany"}],[{"id":8,"name":"Germany"},null]]});
Bets.insert({"_id":"Jpet2dwLqkmaQZy3J","modified":"2016-06-24T13:33:06.934Z","match":[[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[{"id":0,"name":"Switzerland"},{"id":2,"name":"Croatia"}],[{"id":4,"name":"Wales"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":10,"name":"Italy"}],[{"id":13,"name":"Ireland"},{"id":14,"name":"England"}],[{"id":0,"name":"Switzerland"},{"id":7,"name":"Belgium"}],[{"id":10,"name":"Italy"},{"id":13,"name":"Ireland"}],[{"id":7,"name":"Belgium"},{"id":10,"name":"Italy"}],[{"id":10,"name":"Italy"},null]]});
Bets.insert({"_id":"gywgPJKTanGXJZrLz","modified":"2016-06-24T14:02:14.549Z","match":[[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[{"id":0,"name":"Switzerland"},{"id":3,"name":"Portugal"}],[{"id":5,"name":"N. Ireland"},{"id":6,"name":"Hungary"}],[{"id":8,"name":"Germany"},{"id":11,"name":"Spain"}],[{"id":13,"name":"Ireland"},{"id":14,"name":"England"}],[{"id":3,"name":"Portugal"},{"id":6,"name":"Hungary"}],[{"id":11,"name":"Spain"},{"id":14,"name":"England"}],[{"id":6,"name":"Hungary"},{"id":11,"name":"Spain"}],[{"id":6,"name":"Hungary"},null]]});
Bets.insert({"_id":"nkrhm8jvxMMzxwFMQ","modified":"2016-06-24T13:36:52.793Z","match":[[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[{"id":1,"name":"Poland"},{"id":2,"name":"Croatia"}],[{"id":4,"name":"Wales"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":10,"name":"Italy"}],[{"id":12,"name":"France"},{"id":14,"name":"England"}],[{"id":2,"name":"Croatia"},{"id":7,"name":"Belgium"}],[{"id":10,"name":"Italy"},{"id":12,"name":"France"}],[{"id":2,"name":"Croatia"},{"id":10,"name":"Italy"}],[{"id":10,"name":"Italy"},null],[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[null,null],[null,null],[null,null],[null,null],[null,null],[null,null],[null,null],[null,null]]});
Bets.insert({"_id":"p4QuM26Ec65ndGXc8","modified":"2016-06-24T13:36:59.990Z","match":[[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[{"id":1,"name":"Poland"},{"id":2,"name":"Croatia"}],[{"id":4,"name":"Wales"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":14,"name":"England"}],[{"id":2,"name":"Croatia"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":12,"name":"France"}],[{"id":2,"name":"Croatia"},{"id":8,"name":"Germany"}],[{"id":8,"name":"Germany"},null]]});
Bets.insert({"_id":"sk2i22m5MMeQ2Ddpp","modified":"2016-06-24T15:13:25.346Z","match":[[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[{"id":0,"name":"Switzerland"},{"id":2,"name":"Croatia"}],[{"id":4,"name":"Wales"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":10,"name":"Italy"}],[{"id":13,"name":"Ireland"},{"id":14,"name":"England"}],[{"id":2,"name":"Croatia"},{"id":7,"name":"Belgium"}],[{"id":10,"name":"Italy"},{"id":14,"name":"England"}],[{"id":2,"name":"Croatia"},{"id":10,"name":"Italy"}],[{"id":2,"name":"Croatia"},null],[{"id":0,"name":"Switzerland"},{"id":1,"name":"Poland"}],[{"id":2,"name":"Croatia"},{"id":3,"name":"Portugal"}],[{"id":4,"name":"Wales"},{"id":5,"name":"N. Ireland"}],[{"id":6,"name":"Hungary"},{"id":7,"name":"Belgium"}],[{"id":8,"name":"Germany"},{"id":9,"name":"Slovakia"}],[{"id":10,"name":"Italy"},{"id":11,"name":"Spain"}],[{"id":12,"name":"France"},{"id":13,"name":"Ireland"}],[{"id":14,"name":"England"},{"id":15,"name":"Iceland"}],[null,null],[null,null],[null,null],[null,null],[null,null],[null,null],[null,null],[null,null]]});

Meteor.users.insert({"_id":"4EsY3LsENRgayduqY","createdAt":"2016-06-24T13:15:46.360Z","services":{"password":{"bcrypt":"$2a$10$HKx1o3yTZWxuVVWLhVHDc.9Bg/pZb9OwWVtjROzHDmf.8D1oQt3MW"},"resume":{"loginTokens":[{"when":"2016-06-24T13:29:24.844Z","hashedToken":"oZzx4/qCGWNOl/VdyBBifqsuwVlDwamts+beCwDOywE="},{"when":"2016-06-24T19:09:19.250Z","hashedToken":"5JZiGqhtWtqlWO+BLdn0ZWaLuz05KtdyMLXT5BSNGqs="}]}},"emails":[{"address":"joel.barba@one.com","verified":false}]});
Meteor.users.insert({"_id":"8Mgjj9xqSTNNGfzGw","createdAt":"2016-06-24T13:40:52.745Z","services":{"password":{"bcrypt":"$2a$10$tzJW312Peqxn6Sx5uMwUfOKtBoP5740e32YaCn8SEM/5ba.kyTFoK"},"resume":{"loginTokens":[{"when":"2016-06-24T13:40:52.993Z","hashedToken":"3CIeyW5zK3uAn8u0v8etUAtdobOBfXPElceBz41ESiw="}]}},"emails":[{"address":"guillaumebonn@gmail.com","verified":false}]});
Meteor.users.insert({"_id":"DtK4JgXeEd8omDZTE","createdAt":"2016-06-24T13:45:12.248Z","services":{"password":{"bcrypt":"$2a$10$hXOLtcZOgL3g3rACWvH.V.etc/Df6pMy426DngXtEQ6AJDeaQ2bTG"},"resume":{"loginTokens":[{"when":"2016-06-24T13:45:12.497Z","hashedToken":"itBDAoBVE3rde4cfK0L++dpzx5c9dgymdA+f1Cwa9h4="}]}},"emails":[{"address":"vinicius@gmail.com","verified":false}]});
Meteor.users.insert({"_id":"Fw3og7iQrQ5Nky5Q2","createdAt":"2016-06-24T13:31:28.748Z","services":{"password":{"bcrypt":"$2a$10$FXggjSDL67XEpawBvdIzLupe/6ecIaAQBM7UyxAxuqCEw6hEToppy"},"resume":{"loginTokens":[{"when":"2016-06-24T13:31:28.998Z","hashedToken":"kWv8E4sEb0N7ruzeIx03yZB9YVL6uXJADhMNp79ECC8="}]}},"emails":[{"address":"cipolladario@hotmail.it","verified":false}]});
Meteor.users.insert({"_id":"Jpet2dwLqkmaQZy3J","createdAt":"2016-06-24T13:32:51.848Z","services":{"password":{"bcrypt":"$2a$10$yuxVa184WmRUYw7O1Kt/i.0qB5OyN/c/i9IFcbx7O1XPlJpj/xk4y"},"resume":{"loginTokens":[{"when":"2016-06-24T13:32:52.096Z","hashedToken":"Dtk9a5RfC9UmuaFQd1M3ye63z3sLRBQU/KUyFPXPav8="}]}},"emails":[{"address":"pjneri85@gmail.com","verified":false}]});
Meteor.users.insert({"_id":"gywgPJKTanGXJZrLz","createdAt":"2016-06-24T14:01:50.745Z","services":{"password":{"bcrypt":"$2a$10$1qkGnPnTqs6FVw4CpTOpt.rcGQcihYT03uxKwTHxw/FByFJchB6zK"},"resume":{"loginTokens":[{"when":"2016-06-24T14:01:50.993Z","hashedToken":"M+tZwWEC03RHsrdmHKyFoNCWG+gJDzAKG1hDQGsfes0="}]}},"emails":[{"address":"mirko.busu@blueface.com","verified":false}]});
Meteor.users.insert({"_id":"izpFAg3xkeag8vNGF","createdAt":"2016-06-24T15:36:44.045Z","services":{"password":{"bcrypt":"$2a$10$VfDN0apyeqSFxLtwck9ac.9rvARcmC.V.nFQxj65AlBaqx5UXOgra"},"resume":{"loginTokens":[{"when":"2016-06-24T15:36:44.292Z","hashedToken":"6CYNUfcTui7zHequrXwfPirgxAbPyM4Ch7IzmnWemi8="}]}},"emails":[{"address":"feargal@email.com","verified":false}]});
Meteor.users.insert({"_id":"nkrhm8jvxMMzxwFMQ","createdAt":"2016-06-24T13:34:29.741Z","services":{"password":{"bcrypt":"$2a$10$Va0c25c5guNTS3YhaygME.JYtJT1wVcQ8ZHmI2r0epSjMrYbmfGTC"},"resume":{"loginTokens":[{"when":"2016-06-24T13:34:29.990Z","hashedToken":"+2hmcVYNu8AeZ+GaT29l0d8b3f+1eHjCX7KuKA25M0I="}]}},"emails":[{"address":"shanebunyan@gmail.com","verified":false}]});
Meteor.users.insert({"_id":"p4QuM26Ec65ndGXc8","createdAt":"2016-06-24T13:29:30.246Z","services":{"password":{"bcrypt":"$2a$10$SXliSYSC0Q8Kz2BCKQzuWeYipq2UsMnGAiYaXQzUw1KC/h0m/pOcW"},"resume":{"loginTokens":[{"when":"2016-06-24T13:29:30.495Z","hashedToken":"2wzXXxfmy2SsTa8sj5NDpgVFzvWZ5VcBp1LmfkMcUKI="}]}},"emails":[{"address":"tsetko@gmail.com","verified":false}]});
Meteor.users.insert({"_id":"sk2i22m5MMeQ2Ddpp","createdAt":"2016-06-24T15:12:27.944Z","services":{"password":{"bcrypt":"$2a$10$7kFf3LrPPnsAGIs1cRl9pOG8cZTcwujT76Eslae.1ZLFtPCXPlqzW"},"resume":{"loginTokens":[{"when":"2016-06-24T15:12:28.191Z","hashedToken":"Iw2F1pEEKFdmhkLD5NAytOwH2hVQ+AjReTMiKZZiiQY="}]}},"emails":[{"address":"lc@kebu.it","verified":false}]});

*/

	Bets.find({},{}).forEach(function(item) { 
		var usuari = Meteor.users.findOne({_id: item._id},{});
		item.nom = usuari.emails[0].address;
		console.log(item.nom);
      Bets.upsert( item._id, item );
    });

    
    console.log('Initialized');

});



